
###
GET http://localhost:9000/api/test
Accept: application/json
Authorization: Bearer eyJraWQiOiJib29maXQta2V5LWlkIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ0ZXN0IiwibG9naW50eXBlIjoia2FrYW8iLCJpc3MiOiJodHRwczovL3d3dy5ib29rZml0LmNvbSIsIm5pY2tuYW1lIjoidGVzdDIiLCJleHAiOjE3NDk1NzIxMjMsImlhdCI6MTc0OTU3MTIyMywiZW1haWwiOiJ0ZXN0MyJ9.EYDrFe2RhakhXltBdrxC5SJ-MTU5UDSdFglnoIo2gNeWrnQivomAyeQd5O_pXybSAEp_EXfXA8Xl6kiyDzBf_TFoa7nda6-U93DP2eV9KkpM4fZxClWMFqyOhkPeMRuFMR1piX5Gx8JKNB1wFZhyWoSoxzNphqu2AfdHr-Sha8misNSeo2SV7uNaRR1ujUFBfhdPxdSGv1TfJdrU606j6K9RCu3A-J-LKQEY4sQZoIOHO5fWZJi9Z9hvIZw1qzYg26QdqI4HZNXyFOhyQFT5kdNI2ppzpm8_uZAAz3S0T7l4fhAH5uSBngS5NS3eEDVLOcjOcsmA3_gncmu-fGifXg

<> 2025-06-05T021210.200.json
<> 2025-06-05T015214.200.json
<> 2025-06-05T015128.200.json
<> 2025-06-05T015121.200.json

###

GET http://localhost:9010/.well-known/jwks.json
Accept: application/json

<> 2025-06-07T051723.200.json
<> 2025-06-07T035730.200.json
<> 2025-06-07T035725.200.json
<> 2025-06-07T035718.200.json

###

POST http://localhost:9000/api/oauth/token
Content-Type: application/x-www-form-urlencoded


userId = test &
nickname = test2 &
email = test3 &
logintype = kakao

<> 2025-06-07T052052.200.json
<> 2025-06-07T051833.415.json
<> 2025-06-07T051806.415.json
<> 2025-06-07T051803.415.json
<> 2025-06-07T051746.415.json
<> 2025-06-07T051711.415.json
<> 2025-06-07T051444.415.json

###

POST http://localhost:9010/oauth/access-token
Content-Type: application/json

{
  "refresh_token": "test"
}
