
###
GET http://localhost:9000/api/test
Accept: application/json
Authorization: Bearer eyJraWQiOiJib29maXQta2V5LWlkIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ0ZXN0IiwibG9naW50eXBlIjoia2FrYW8iLCJpc3MiOiJodHRwczovL3d3dy5ib29rZml0LmNvbSIsIm5pY2tuYW1lIjoidGVzdDIiLCJleHAiOjE3NDk5MzE2OTgsImlhdCI6MTc0OTkzMDc5OCwiZW1haWwiOiJ0ZXN0MyJ9.OvPx-mIU-gu74ZEC6Gzk3FTdhw5hEYL5ABvojYGKIL5YFDkZhAY7eX5D0R7tfCCEYriTca-lJXJJiQn6my00GuLNmS7a1sY9xHgNl7eGq5s7sdXCAOnvmrrBmqcRJY7BKJwTFgiSDsIdCLsXdsvtFoCe_iH9c9buaLM07yeif7qf4wYxRh3w7zx45SwL2x7SJLUbBOOGi7H-ZN-EQsdSrvu1tL3-qzkuLEzYrMYp07SkqEEnjwDz5la9hY73aNa-74ru7e57XSOMx9XY1Hb1ZiQfv1zcruh08avAxv_DEr6O7JLrVYU9mCwjJfCgCTsuqzgYTYfG4kBB4sk96-iExg

<> 2025-06-05T021210.200.json
<> 2025-06-05T015214.200.json
<> 2025-06-05T015128.200.json
<> 2025-06-05T015121.200.json

###

GET http://localhost:9010/.well-known/jwks.json
Accept: application/json

<> 2025-06-07T051723.200.json
<> 2025-06-07T035730.200.json
<> 2025-06-07T035725.200.json
<> 2025-06-07T035718.200.json

###

POST http://localhost:9000/api/oauth/token
Content-Type: application/x-www-form-urlencoded


userId = test &
nickname = test2 &
email = test3 &
logintype = kakao

<> 2025-06-07T052052.200.json
<> 2025-06-07T051833.415.json
<> 2025-06-07T051806.415.json
<> 2025-06-07T051803.415.json
<> 2025-06-07T051746.415.json
<> 2025-06-07T051711.415.json
<> 2025-06-07T051444.415.json

###

POST http://localhost:9000/api/oauth/access-token
Content-Type: application/json

{
  "refresh_token": "test"
}

###


# curl -X POST --location "http://localhost:9000/api/oauth/token"
#    -H "Content-Type: application/x-www-form-urlencoded"
#    -d 'userId=test&nickname=test2&email=test3@test.com&logintype=kakao'
POST http://localhost:9000/api/oauth/token
Content-Type: application/x-www-form-urlencoded

userId = test &
nickname = test2 &
email = test3@test.com &
logintype = kakao

###

